version: '3'
services:
  db:
    build: db
    image: db:v1
    container_name: ws-db
    volumes: 
      - ./db/postgresdata:/bitnami/postgresql
    ports:
      - 5432:5432
    networks:
      - wordsmith_net    
  words:
    build: words
    image: words:v1
    container_name: ws-words
    command: ["java","-Xmx9m","-Xms9m","-jar","target/words.jar"]
    depends_on: 
      - db
    ports:
      - 8080:8080
    networks:
      - wordsmith_net    
  web:
    build: web
    image: web:v1
    container_name: ws-web
    depends_on:
      - words
    command: ["./dispatcher"]
    ports:
      - 80:80
    networks:
      - wordsmith_net
networks:
  wordsmith_net:
    driver: bridge
